### ISSUE TITLE
Get forecasts from RAP and NAM

### ISSUE THREAD

**Issue by rbessa** [oscarperpinan/meteoForecast#17]
The getPoint for the RAP and NAM models does not seem to be working:

> v_wind <- getPoint(c(-112, 43), vars = 'V-component_of_wind',service='rap')
> Error in pointNCDC(lon = lon, lat = lat, vars = vars, day = day, run = run,  : 
>    no data could be retrieved. Check date, coordinates and variable(s).

_One suggestion: add an example with RAP and NAM to the R Documentation_

**Comment by oscarperpinan** [comment]
Due to the configuration of the NCDC servers, the `getRaster` function usually gets better results than `getPoint`. For your example this should work:

```
x <- getRaster('V-component_of_wind', day = testDay, 
                          box = c(-115, -110, 41, 45), 
                          frames = 10, service = 'rap')
```
However, it seems that the RAP service is now temporarily unavailable. I will try later.

On the other hand, thanks for the suggestion: I will add more examples.

**Comment by rbessa** [comment]
There is a delay in the NAM and RAP server. For some reason they only have data until 20160412. If we choose another date (like 5 years) it works.
